Software Engineering Group Project/carbongram/views.py
import base64
import copy
import os
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from carbongram.forms import CreatePost, CreateComment
from models import SocialPosts, User, SocialPostLikes, SocialPostComments, UserFriends, ReportedUser, ReportedPost
from app import db

# Config
carbongram_blueprint = Blueprint('carbongram', __name__, template_folder='templates')


@login_required
@carbongram_blueprint.route('/carbongram')
def carbongram():
    """ Render the carbongram main page. """
    # Get all current posts and users
    Posts = SocialPosts.query.all()
    Users = User.query.all()

    postInfo = []
    print(Posts)
    # Make copies of posts
    if Posts:
        PostsCopies = list(map(lambda x: copy.deepcopy(x), Posts))

        # Find out more data for each post such as likes and comments
        # then add all data to 2D array postInfo
        for post in PostsCopies:
            for user in Users:
                if post.UserId == user.id:
                    postLikes = SocialPostLikes.query.filter_by(PostId=post.PostId).all()
                    postLiked = True if 0 < len(
                        SocialPostLikes.query.filter_by(PostId=post.PostId, UserId=current_user.id).all()) else False
                    CommentTotal = len(SocialPostComments.query.filter_by(PostId=post.PostId).all())
                    userF = UserFriends.query.filter_by(user1_id=current_user.id, user2_id=post.UserId).first()
                    userF1 = UserFriends.query.filter_by(user1_id=post.UserId, user2_id=current_user.id).first()
                    friend = False
                    if userF or userF1:
                        friend = True
                    postInfo.append([post, user, postLikes, postLiked, CommentTotal, friend])

        return render_template('carbongram.html', AllPosts=postInfo[::-1], form=CreatePost(), hasNav=True)

    return render_template('carbongram.html')


@login_required
@carbongram_blueprint.route('/add_post', methods=['GET', 'POST'])
def add_post():
    """ Add a new post to the database. """
    if request.method == 'POST':
        if request.form['submit_button'] == 'Post':
            if request.form["text_area"] == "What's on your mind?" or None:
                return carbongram()

            postImage = None
            if request.files['userpostimage']:
                pic = request.files['userpostimage']
                pic.save(os.path.join('static/images', secure_filename(pic.filename)))
                with open('static/images/' + pic.filename, "rb") as img_file:
                    postPic = base64.b64encode(img_file.read())
                postImage = postPic
                os.remove('static/images/' + pic.filename)


            post = SocialPosts(
                UserId=current_user.id,
                PostText=request.form["text_area"],
                PostImg=postImage
            )
            db.session.add(post)
            db.session.commit()

    return redirect(url_for('carbongram.carbongram', form=CreatePost()))


@login_required
@carbongram_blueprint.route('/delete_post', methods=['GET', 'POST'])
def delete_post():
    """ Delete a post from the database. """
    if request.method == 'POST':
        if request.form['submit_button'] == 'Delete Post':
            postId= int(request.form['carbongramDeletePost'])

            SocialPosts.query.filter(SocialPosts.PostId == postId).delete()
            SocialPostLikes.query.filter_by(PostId=postId).delete()
            SocialPostComments.query.filter_by(PostId=postId).delete()
            db.session.commit()

    return redirect(url_for('carbongram.carbongram'))


@login_required
@carbongram_blueprint.route('/like_post', methods=['GET', 'POST'])
def like_post():
    """ Increase the amount of likes on a post. """
    if request.method == 'POST':
        like = SocialPostLikes(
            PostId=request.form['like'],
            UserId=current_user.id
        )
        db.session.add(like)
        db.session.commit()

    return redirect(url_for('carbongram.carbongram'))


@login_required
@carbongram_blueprint.route('/unlike_post', methods=['GET', 'POST'])
def unlike():
    """ Decrease the amount of like on a post. """
    if request.method == 'POST':
        unlike = SocialPostLikes.query.filter_by(PostId=request.form['unlike'], UserId=current_user.id).first()
        db.session.delete(unlike)
        db.session.commit()

    return redirect(url_for('carbongram.carbongram'))


@login_required
@carbongram_blueprint.route('/update/<int:id>', methods=('GET', 'POST'))
def updatePost(id):
    """ Update a post with changes. """
    post = SocialPosts.query.filter_by(PostId=id,UserId=current_user.id).first()
    if not post:
        return redirect(url_for('carbongram.carbongram'))

    form = CreatePost()

    if request.method == 'POST':
        if form.validate_on_submit():
            postImage = None
            if request.files['userpostimage']:
                pic = request.files['userpostimage']
                pic.save(os.path.join('static/images', secure_filename(pic.filename)))
                with open('static/images/' + pic.filename, "rb") as img_file:
                    postPic = base64.b64encode(img_file.read())
                postImage = postPic
                os.remove('static/images/' + pic.filename)


            SocialPosts.query.filter_by(PostId=id).update({"PostText": request.form["updatedPost"],"PostImg":postImage})
            db.session.commit()
            return redirect(url_for('carbongram.carbongram'))

    return render_template('carbongramUpdatePost.html', form=form, post=post, hasNav=True)


@login_required
@carbongram_blueprint.route('/comment/<int:id>', methods=('GET', 'POST'))
def commentPost(id):
    """ Add a comment to SocialPostComments and a post. """
    posts = SocialPosts.query.filter_by(PostId=id).first()
    user = User.query.filter_by(id=posts.UserId).first()
    postComments = []
    post = [posts, user]

    form = CreateComment()

    if not posts:
        return redirect(url_for('carbongram.carbongram'))

    comments = SocialPostComments.query.all()
    try:
        for i in comments:
            if i.PostId == id:
                userComment = User.query.filter_by(id=i.UserId).first()
                postComments.append([i, userComment])
    except():
        pass

    post.append(postComments)
    if request.method == 'POST':
        if form.validate_on_submit():
            if not form.comment.data == "":
                postComment = SocialPostComments(
                    PostId=id,
                    CommentText=form.comment.data,
                    UserId=current_user.id
                )
                db.session.add(postComment)
                db.session.commit()
        return redirect(url_for('carbongram.commentPost', id=id))

    return render_template('carbongramAddComment.html', form=form, post=post, hasNav=True)


@login_required
@carbongram_blueprint.route('/search_for_friend', methods=('GET', 'POST'))
def search_for_friend():
    if request.method == 'POST':
        if len(request.form['searchForFriend']) > 0:
            return search_friend(username=request.form['searchForFriend'])
        else:
            return redirect(url_for('carbongram.carbongram'))


@login_required
@carbongram_blueprint.route('/search/<string:username>', methods=('GET', 'POST'))
def search_friend(username):
    users = User.query.filter(User.id != current_user.id).all()
    userF = UserFriends.query.filter_by(user1_id=current_user.id).all()
    userF1 = UserFriends.query.filter_by(user2_id=current_user.id).all()

    friends = userF + userF1

    searchUser = []
    try:
        for user in users:
            if username.upper() in user.username.upper():

                if UserFriends.query.filter_by(user1_id=current_user.id, user2_id=user.id).first():
                    searchUser.append([user, True])

                elif UserFriends.query.filter_by(user2_id=current_user.id, user1_id=user.id).first():
                    searchUser.append([user, True])

                else:
                    searchUser.append([user, False])

        return render_template('carbongramSearchFreinds.html', users=searchUser, form=CreatePost(), hasNav=True)
    except():
        if len(searchUser) == 0:
            return render_template('carbongramSearchFreinds.html', notFound=True, form=CreatePost(), hasNav=True)


@carbongram_blueprint.route('/profile/<string:username>/<int:id>', methods=('GET', 'POST'))
def userProfile(username, id):
    user = User.query.filter_by(id=id).first()
    Posts = SocialPosts.query.filter_by(UserId=id).all()
    postInfo = []

    if Posts:
        PostsCopies = list(map(lambda x: copy.deepcopy(x), Posts))

        for post in PostsCopies:
            if post.UserId == user.id:
                postLikes = SocialPostLikes.query.filter_by(PostId=post.PostId).all()
                postLiked = True if 0 < len(
                    SocialPostLikes.query.filter_by(PostId=post.PostId, UserId=id).all()) else False
                CommentTotal = len(SocialPostComments.query.filter_by(PostId=post.PostId).all())
                userF = UserFriends.query.filter_by(user1_id=id, user2_id=post.UserId).first()
                userF1 = UserFriends.query.filter_by(user1_id=post.UserId, user2_id=id).first()
                friend = False
                if userF or userF1:
                    friend = True
                postInfo.append([post, user, postLikes, postLiked, CommentTotal, friend])

    accFriend = []

    userF = UserFriends.query.filter(UserFriends.user1_id == id).limit(6).all()
    userF1 = UserFriends.query.filter(UserFriends.user2_id == id).limit(6).all()
    friend = False
    friends = userF + userF1
    if friends:
        for friend in friends:

Software Engineering Group Project/information/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user
from app import db
from models import FAQ, UsefulLinks, User, SurveyResult, UserFriends
from sqlalchemy import or_

# Config
information_blueprint = Blueprint('information', __name__, template_folder='templates')


@information_blueprint.route('/reduce')
def reduce():
    """ Render the reduce page. """
    return render_template('reduce.html', hasNav=True)


@information_blueprint.route('/FAQ')
def loadFAQ():
    """ Render FAQ page with all FAQs stored in database. """
    # Only shows FAQs that have been approved
    questionAndAnswer = FAQ.query.filter_by(approved=1).all()

    return render_template('FAQ.html', FAQ=questionAndAnswer, hasNav=True)


@information_blueprint.route('/FAQsubmit', methods=["POST"])
def FAQsubmit():
    """ Get inputted question and add it to database. """
    questionAndAnswer = []
    try:
        questionAndAnswer = FAQ.query.filter_by(approved=1).all()
    except():
        pass
    question = request.form.get("FAQQuestion")

    questionToSubmit = FAQ(question=question, answer="", approved=0)
    db.session.add(questionToSubmit)
    db.session.commit()


    return render_template('FAQ.html', FAQ=questionAndAnswer, hasNav=True)


@information_blueprint.route('/usefulLinks')
def usefulLinks():
    """ Render the useful links page with all links stored in the database."""
    links = UsefulLinks.query.all()

    return render_template('usefulLinks.html', links=links, hasNav=True)


@information_blueprint.route('/leaderboard')
def leaderboard():
    """ Render the leaderboard page. """
    return render_template('leaderboard.html', hasNav=True)


@information_blueprint.route('/worldLeaderboard', methods=['POST'])
def worldLeaderboard():
    """ Find out the 10 users with the lowest current footprint out of all users. """
    leaders = []
    # Get all users
    users = User.query.all()
    # For each user get a list of all their recorded footprints
    for user in users:
        footprints = SurveyResult.query.filter_by(user_id=user.id).all()
        if len(footprints) > 0:
            # Find the most recent footprint and add it to leaders along with the user
            leaders.append((user, mostRecentFootprint(footprints)))

    # Sort all footprints
    insertionSortFootprint(leaders)

    return render_template('leaderboard.html', leaders=leaders[:10], type="WORLD", hasNav=True)


@information_blueprint.route('/friendLeaderboard', methods=['POST'])
def friendLeaderboard():
    """ Find out the 10 users with the lowest current footprint out of your friends. """
    leaders = []
    users = set()
    # Get all friend records
    records = UserFriends.query.filter(or_(UserFriends.user1_id == current_user.id
                                           , UserFriends.user2_id == current_user.id)).all()

    # Add both ideas to a set so there is no duplicates
    if len(records) > 0:
        for record in records:
            users.add(User.query.filter_by(id=record.user1_id).first())
            users.add(User.query.filter_by(id=record.user2_id).first())

    # Turn set into a list so it can be amended
    users = list(users)

    # Get all of a users footprints
    for user in users:
        footprints = SurveyResult.query.filter_by(user_id=user.id).all()
        if len(footprints) > 0:
            # # Find the most recent footprint and add it to leaders along with the user
            leaders.append((user, mostRecentFootprint(footprints)))

    # Sort all footprints
    insertionSortFootprint(leaders)

    return render_template('leaderboard.html', leaders=leaders, type="FRIENDS",hasNav=True)


def mostRecentFootprint(list):
    """ Find which footprint is the most recent and return it. """
    # Set most recent data and date object
    recentEmissions = list[0].date
    recent = list[0]

    for i in range(0, len(list)):
        # Compare date
        if list[i].date < recentEmissions:
            # If more recent amend most recent date and date object
            recentEmissions = list[i].date
            recent = list[i]

    return recent


def insertionSortFootprint(list):
    """ Insertion sort based on carbon equivelents, but sorts tuple order for leaderboard. """
    for i in range(1, len(list)):
        # Set the item (tuple) in the list, but also need the key value (float) which is the
        # amount of carbon equivalents of each footprint
        item = list[i]
        key = list[i][1].carbon_emissions
        j = i

        # Make sure to check against carbon equivalents not object
        while j > 0 and key < list[j-1][1].carbon_emissions:
            list[j] = list[j-1]
            j = j-1

        # Move items around
        list[j] = item

Software Engineering Group Project/quiz/views.py
from flask import Blueprint, render_template, request, session
from flask_login import current_user
from models import QuizResult
from app import db

# Config
quiz_blueprint = Blueprint('quiz', __name__, template_folder='templates')


@quiz_blueprint.route('/quiz')
def quiz():
    """ This function is to view the quiz home page. """
    return render_template('quiz-home.html', hasNav=True)


@quiz_blueprint.route('/quiz_questions_general')
def quiz_questions_general():
    """ This function is to view the quiz questions general page. """
    return render_template('quiz_questions_general.html', hasNav=False)


@quiz_blueprint.route('/quiz_questions_advanced')
def quiz_questions_advanced():
    """ This function is to view the quiz questions advanced page. """
    return render_template('quiz_questions_advanced.html', hasNav=False)


@quiz_blueprint.route('/general', methods=['POST'])
def count_general_quiz():
    """ This function is to calculate the overall score for the general quiz. """

    score = 0
    sample_general_answer = "11111DBADE"
    user_answer = ""
    # get user's answers from form
    for i in range(1, 11):
        user_answer += request.form.get("choice" + str(i))
    for j in range(len(sample_general_answer)):
        if user_answer[j] == sample_general_answer[j]:
            score += 1

    session['general_quiz_answer'] = user_answer
    session['general_quiz_score'] = score

    if current_user.is_authenticated:
        new_quiz_result = QuizResult(user_id=current_user.id,
                                     user_answer=user_answer,
                                     user_mark=score,
                                     quiz_category="general")
        db.session.add(new_quiz_result)
        db.session.commit()

    return render_template("quiz_result.html", quiz_score=score, hasNav=True)


@quiz_blueprint.route('/advance', methods=['POST'])
def count_advance_quiz():
    """ This function is to calculate the overall score for the advance quiz. """
    score = 0
    sample_advance_answer = "00011CCCCB"
    user_answer = ""
    # get user's answers from form
    for i in range(11, 21):
        user_answer += request.form.get("choice" + str(i))
    for j in range(len(sample_advance_answer)):
        if user_answer[j] == sample_advance_answer[j]:
            score += 1

    session['advance_quiz_answer'] = user_answer
    session['advance_quiz_score'] = score
    if current_user.is_authenticated:
        new_quiz_result = QuizResult(user_id=current_user.id,
                                     user_answer=user_answer,
                                     user_mark=score,
                                     quiz_category="advance")
        db.session.add(new_quiz_result)
        db.session.commit()
    return render_template("quiz_result.html", quiz_score=score, hasNav=True)

Software Engineering Group Project/templates/FAQ.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_authenticated %}
    {% if current_user.background != None %}
     {% set backgroundImg = current_user.background | string() %}
     {% set backgroundImg = backgroundImg.split("b'")[1].split("'")[0] %}
        {% endif %}
    {% endif %}

    <div class="carbongramMainbody" {% if backgroundImg %}
     style="background-image: url('data:image/png;base64,{{ backgroundImg }}');justify-content: center" {% endif %}>

    <div id="adminDisplay" >
    <div class="InformationContainerCon" >
            <div class="InformationContainer" >
                <h1>FAQ</h1>
                {% for faq in FAQ %}
                    <div class="Info">
                        <div class="question">
                            <h2>{{ faq.question }}</h2>
                        </div>
                        <div class="answer">
                            <p>{{ faq.answer }}</p>
                        </div>
                    </div>
                {% endfor %}
                <form method="post" action="/FAQsubmit">
                    <p>DO YOU HAVE ANY QUESTIONS?</p>
                    <input type="text" id="q" name="FAQQuestion" placeholder="Question?">
                    <button class="buttonMedium" id="createPostBodyButton">SUBMIT</button>
                </form>
            </div>
        </div>
    </div>

    </div>

{% endblock %}

Software Engineering Group Project/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div id="profileDeleteCon">
            <form  id="profileDeleteForm" method="POST" >
                <div id="profileDeleteText">
                    <h2>Are you sure you want to delete your account?</h2>
                </div>
                    <div class="profileButton" id="profileDeleteAcConButton">
                        <input type="submit" class="quizWrong" name="submit_button" value="Delete Profile">
                        <button id="profileButtonR" class="buttonMedium" type="button" >Return</button>
                    </div>

            </form>
        </div>

    <div class="background">
    <img id="userBackground" src="../static/img/kerala-2.jpg"/>
</div>
<div class="flex background-container profile-main" {% if current_user.background %}
     {% set backgroundImg = current_user.background | string() %}
     {% set backgroundImg = backgroundImg.split("b'")[1].split("'")[0] %}
     style="background-image: url('data:image/png;base64,{{ backgroundImg }}');background-repeat: no-repeat;background-size: cover;" {% endif %}>


    <div class="col-md-7 col-sm-7 profile-left">
    <div id="profileSidebar">
        <div class="profileTitle">
            <h2>Profile</h2>
        </div>

        <div id="profileContainer" >
            <form  id="profileForm" method="POST" enctype = "multipart/form-data">
            <div id="profileCon">
                <div id="profileCarbonCurCarbonCon">
                    <div id="footprintTitle">
                        <h3>Current Footprint</h3>
                    </div>
                    <div id="footprint">
                        {% if currentFootprint %}
                            {% set footprint = currentFootprint.footprint | string() %}
                            {% set footprint = footprint.split("b'")[1].split("'")[0] %}
                        <img src="data:image/png;base64,{{ footprint }}" />
                            <div id="footprintExp">
                            <p style="background-color: #4a8522;">FOOD: {{ currentFootprint.food }}</p>
                            <p style="background-color: #be5108;">TRANSPORT: {{ currentFootprint.transport }}</p>
                            <p style="background-color: #1d4999;">PURCHASING: {{ currentFootprint.purchasing }}</p>
                            <p style="background-color: #d29500;">ENERGY: {{ currentFootprint.energy }}</p>
                            </div>

                        {% endif %}
                    </div>
                </div>
                {% set profilePic = current_user.profile_picture | string() %}
                {% set profilePic = profilePic.split("b'")[1].split("'")[0] %}
                <div id="profilePic" >
                    <a id="profilePicCon">
                        <img id="profilePicture" src="data:image/png;base64,{{ profilePic }}" alt=""/>
                        <label for="userProfilePic" class="customCoverupLoad" id="profileCustomProfileLoad">
                            <i class="fa fa-cloud-upload"></i> Upload Picture
                        </label>
                        <input accept="image/*" type='file' name="userProfilePic" id="userProfilePic" onchange="readURL(this);" >
                    </a>
                </div>
            </div>

            <div class="profileSetContainer">
                <div id="profileSettingsConLeft">
                {{ form.csrf_token() }}
                    <div id="error">
                        {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="notification is-danger">
                                    {{ messages[0] }}
                                </div>
                            {% endif %}
                        {% endwith %}
                    </div>
                    <div class="ProfileinputB">
                            <p>Username</p>
                            {{ form.username(class="profileFormInput", value=current_user.username ) }}
                            <div class="errorHolder">
                                {% for error in form.username.errors %}
                                    <p id="registerError">{{ error }}</p>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="ProfileinputB">
                            <p>First Name</p>
                            {{ form.firstname(class="profileFormInput", value=current_user.firstname ) }}
                            <div class="errorHolder">
                                {% for error in form.firstname.errors %}
                                    <p id="registerError">{{ error }}</p>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="ProfileinputB">
                            <p>Surname</p>
                            {{ form.surname(class="profileFormInput", value=current_user.surname ) }}
                            <div class="errorHolder">
                                {% for error in form.surname.errors %}
                                    <p id="registerError">{{ error }}</p>
                                {% endfor %}
                            </div>
                        </div>
                        <div id="profileSubButton">
                            <input  class="buttonMedium" type="submit" name="submit_button" value="Confirm">
                        </div>
                     <div  id="profileSubButton">
                            <p>Change Password</p>
                            <input  class="buttonMedium" type="submit" name="submit_button" value="Click to Change">
                      </div>
                    <div class="profileButton">
                        <button id="profileButtonB" class="quizWrong" type="button">Delete Profile</button>
                    </div>
                </div>

                <div id="profileSettingsConRight">
                    <div id="profileBackground">
                        <div id="profileBackgroundPreset">
                            <img id="backgroundImages" src="data:image/png;base64,{{ backgroundImg }}" style="border: 1px black solid;" />
                        </div>
                            <div class="profileBackgroundButtons">
                                <p>Changing Background may impact Performance</p>
                                <a>
                                    <label for="userprofileBackground" class="customCoverupLoad" id="profileCustomProfileLoad">
                                        <i class="fa fa-cloud-upload"></i> Upload Background
                                    </label>
                                    <input accept="image/*" type='file' name="userprofileBackground" id="userprofileBackground" onchange="readURL(this);"/>
                                </a>
                            </div>
                    </div>

                    {% if quizResult %}
                    <div id="profileQuiz">
                        <h4>Quiz Score</h4>

                        <div id="profileQuizScore">
                            {% for quiz in quizResult %}
                            <div id="quizScoreCon">
                                <h5>{{ quiz.quiz_category }}</h5>
                                <div id="quizBarCon">
                                    {% set rightW = (quiz.user_mark / 10) *100  %}
                                    {% set wrong = 100 -rightW%}
                                    <div id="quizBarText">
                                        <h6>{{ rightW }}%</h6>
                                        <h6>{{ wrong }}%</h6>
                                    </div>
                                    <div id="quizBars">
                                        <div id="quizBar" class="quizRight" style="width: {{ rightW}}%;border-top-left-radius: 8px;border-bottom-left-radius: 8px;"></div>
                                        <div id="quizBar" class="quizWrong" style="width:{{ wrong }}%;border-top-right-radius: 8px;border-bottom-right-radius: 8px;"></div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                    </div>
                    {% endif %}

                </div>
            </div>
            </form>
        </div>

    </div>


    </div>
    <div class="col-md-5 col-sm-5" id="profileRightBar">
        <div class="profileRContainer">
            <div class="profileTitle">
                <h2>Previous Carbon Footprints</h2>
            </div>

            <div id="footprintsContainer">
                {% if pastFootprint %}
                    {% for footprints in pastFootprint %}
                        <div id="footprintCarbonCurCarbonCon">
                        {% set scale = footprints.carbon_emissions * 10 %}
                            <div id="footprint" >
                            {% set footprint = footprints.footprint | string() %}
                            {% set footprint = footprint.split("b'")[1].split("'")[0] %}
                                <img src="data:image/png;base64,{{ footprint }}" style="height: {{scale }}%;"/>
                            </div>
                            <div id="footprintTitle">
                                <h4>{{ footprints.carbon_emissions }}</h4>
                                <h4>{{ footprints.date.strftime('%d/%m/%y') }}</h4>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

        </div>

        <div class="profileRContainer">
            <div class="profileTitle">
                <h2>Friends</h2>
            </div>

            <div id="footprintsContainer">

            {% if friends %}
               {% for friend in friends %}
                <div id="friendContainer">
                    <div id="friendProfile">
                        {% set PprofilePic = friend.profile_picture | string() %}
                        {% set PprofilePic = PprofilePic.split("b'")[1].split("'")[0] %}
                         <a href="{{ url_for('carbongram.userProfile',username=friend.username,id=friend.id ) }}">
                             <img src="data:image/png;base64,{{ PprofilePic }}"  />
                         </a>
                    </div>
                    <div id="friendName">
                        <h5>{{ friend.username }}</h5>
                    </div>

                    <div id="friendButtons">
                        <button id="" class="buttonMedium">Message</button>
                        <form method="POST"  id="search_friend" action="/delFriend">
                            <button id="deleteFriend" class="quizWrong"  name="removeFriend" value="{{ friend.id }}">Delete</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div id="friendContainer">
            <h3>No friends</h3>
                </div>
            {% endif %}


        </div>

        </div>
    </div>
</div>
 <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

Software Engineering Group Project/templates/quiz-home.html
{% extends "base.html" %}

{% block content %}
<div class="background">
    <img src="../static/img/quiz-background.jpg"/>
</div>
<div class="flex background-container">
    <div class="header content-centre">
        <div class="container-light">
            <h2 class="subtitle">Climate Change Quiz</h2>
            <div>
                <a class="quiz-btn" href="{{ url_for('quiz.quiz_questions_general') }}">General</a>
                <a class="quiz-btn" href="{{ url_for('quiz.quiz_questions_advanced') }}">Advanced</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}